### ISSUE TITLE
CI doesn't really do anything for this repo…

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/n-cookie-message#15]
Hi @ifyio as owner would you mind taking a look at this when you're back?

I made a basic mistake that could been caught by linting and it wasn't.  Also `make test` currently errors, again CI doesn't fail because of the build.

Suggest setting this repo's CI up like all the other apps… some instructions are here:-
http://financial-times.github.io/next/docs/developer-guide/circle/

I can help if you need :-)

**Comment by ifyio** [comment]
sure no prob.
